-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 001_create_events.sql
-- Biomorphic Enterprise — Memory Layer
--
-- Creates the core events table, pgvector embedding index,
-- and supporting tables for accuracy scoring and mode promotion.
--
-- Requires: pgvector extension (available on Supabase by default)
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable pgvector
create extension if not exists vector;
create extension if not exists "uuid-ossp";

-- ─────────────────────────────────────────────────────────────────────────────
-- source_type enum — mirrors BiomorphicEvent.SourceType in proto
-- ─────────────────────────────────────────────────────────────────────────────
create type source_type as enum (
  'transaction',
  'entity',
  'external',
  'document',
  'cortex',
  'actor'
);

-- ─────────────────────────────────────────────────────────────────────────────
-- events — one row per BiomorphicEvent written to the spine
--
-- This table is the long-term semantic memory layer.
-- Every event written to Kafka is also written here with its embedding.
-- Cortex performs K-NN retrieval against the embedding column
-- to inject semantically similar historical events into attention context.
--
-- APPEND-ONLY: rows are never updated or deleted in production.
-- ─────────────────────────────────────────────────────────────────────────────
create table events (
  -- ── Identity (mirrors proto fields 1–4) ───────────────────────────────────
  event_id      uuid          primary key default uuid_generate_v4(),
  timestamp     timestamptz   not null,
  source_type   source_type   not null,
  receptor_id   text          not null,

  -- ── Signal (proto field 5) ────────────────────────────────────────────────
  -- Raw payload bytes from the spine event.
  -- Stored for audit and replay. Not queried directly.
  payload       bytea         not null,

  -- ── Confidence (proto field 6) ────────────────────────────────────────────
  confidence    real          not null check (confidence >= 0.0 and confidence <= 1.0),

  -- ── Semantic embedding ────────────────────────────────────────────────────
  -- d_s = 512 dimensions (OpenAI text-embedding-3-small or SentenceTransformer)
  -- Generated by EmbeddingProvider at write time.
  -- Used by Cortex for K-NN retrieval of semantically similar past events.
  embedding     vector(512),

  -- ── Audit ─────────────────────────────────────────────────────────────────
  -- When this row was written to Supabase (may differ slightly from timestamp).
  inserted_at   timestamptz   not null default now()
);

-- ── Indexes ──────────────────────────────────────────────────────────────────

-- Primary K-NN index for Cortex semantic retrieval.
-- HNSW is preferred over IVFFlat for low-latency approximate nearest neighbour.
-- ef_construction=128, m=16 are sensible defaults; tune per data volume.
create index events_embedding_hnsw
  on events
  using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 128);

-- Time-range queries (recent event window for Cortex temporal context).
create index events_timestamp_idx
  on events (timestamp desc);

-- Filter by source type (e.g. fetch only CORTEX events for scoring).
create index events_source_type_idx
  on events (source_type, timestamp desc);

-- Filter by producer (e.g. fetch all events from a specific receptor).
create index events_receptor_idx
  on events (receptor_id, timestamp desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- accuracy_scores — rolling accuracy log for the scoring engine
--
-- One row per scored prediction: Cortex prediction vs actor decision.
-- Used to compute rolling accuracy per source_type for mode promotion.
-- ─────────────────────────────────────────────────────────────────────────────
create table accuracy_scores (
  id                  bigserial     primary key,
  scored_at           timestamptz   not null default now(),

  -- The Cortex prediction event being scored.
  cortex_event_id     uuid          not null references events(event_id),

  -- The actor decision event it is being compared against.
  actor_event_id      uuid          not null references events(event_id),

  -- The signal type this prediction relates to.
  source_type         source_type   not null,

  -- Whether Cortex prediction matched actor decision.
  hit                 boolean       not null,

  -- Cortex confidence at time of prediction.
  cortex_confidence   real          not null,

  -- Actor confidence at time of decision.
  actor_confidence    real          not null
);

create index accuracy_scores_source_type_idx
  on accuracy_scores (source_type, scored_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- mode_promotions — audit log of every mode transition
--
-- Append-only record of every learning→execution and execution→learning
-- transition. Written by the promotion orchestrator.
-- Also written as a CORTEX event to the Kafka spine for full auditability.
-- ─────────────────────────────────────────────────────────────────────────────
create table mode_promotions (
  id                    bigserial     primary key,
  promoted_at           timestamptz   not null default now(),

  from_mode             text          not null check (from_mode in ('learning', 'execution')),
  to_mode               text          not null check (to_mode   in ('learning', 'execution')),

  -- Accuracy snapshot at promotion time.
  accuracy              real          not null,
  window_days           integer       not null,
  scored_predictions    bigint        not null,

  -- Whether this was automatic (threshold-triggered) or manual (operator).
  triggered_by          text          not null check (triggered_by in ('auto', 'operator')),

  -- The spine event_id of the promotion event written to Kafka.
  -- Allows full cross-reference between Supabase audit and spine replay.
  spine_event_id        uuid          references events(event_id),

  -- Operator notes (for manual promotions / rollbacks).
  notes                 text
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Helper view: rolling accuracy per source_type over last 30 days
-- ─────────────────────────────────────────────────────────────────────────────
create view rolling_accuracy as
select
  source_type,
  count(*)                                          as total_scored,
  sum(case when hit then 1 else 0 end)              as hits,
  round(
    sum(case when hit then 1 else 0 end)::numeric
    / nullif(count(*), 0) * 100, 2
  )                                                 as accuracy_pct,
  min(scored_at)                                    as window_start,
  max(scored_at)                                    as window_end
from accuracy_scores
where scored_at >= now() - interval '30 days'
group by source_type;

-- ─────────────────────────────────────────────────────────────────────────────
-- Helper function: K-NN retrieval for Cortex
--
-- Returns the top-k most semantically similar past events to a query vector.
-- Called by Cortex during inference to inject long-term memory into context.
--
-- Usage:
--   select * from match_events(query_embedding, 0.75, 10);
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function match_events (
  query_embedding   vector(512),
  match_threshold   float    default 0.75,
  match_count       int      default 10
)
returns table (
  event_id      uuid,
  timestamp     timestamptz,
  source_type   source_type,
  receptor_id   text,
  payload       bytea,
  confidence    real,
  similarity    float
)
language sql stable
as $$
  select
    e.event_id,
    e.timestamp,
    e.source_type,
    e.receptor_id,
    e.payload,
    e.confidence,
    1 - (e.embedding <=> query_embedding) as similarity
  from events e
  where e.embedding is not null
    and 1 - (e.embedding <=> query_embedding) > match_threshold
  order by e.embedding <=> query_embedding
  limit match_count;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Row-level security (RLS)
-- Enable for production deployments. Disable for local dev.
-- ─────────────────────────────────────────────────────────────────────────────
-- alter table events          enable row level security;
-- alter table accuracy_scores enable row level security;
-- alter table mode_promotions enable row level security;
